/** 产品详情浏览统计 */
export const PRODUCT_SHARED_VIEW_COUNT_START = 'PRODUCT_SHARED_VIEW_COUNT_START'
export const PRODUCT_SHARED_VIEW_COUNT_SUCCESS = 'PRODUCT_SHARED_VIEW_COUNT_SUCCESS'
export const PRODUCT_SHARED_VIEW_COUNT_FAIL = 'PRODUCT_SHARED_VIEW_COUNT_FAIL'
export const PRODUCT_SHARED_VIEW_COUNT_END = 'PRODUCT_SHARED_VIEW_COUNT_END'
/** 产品详情浏览统计 */

/** 产品详情分享统计 */
export const PRODUCT_SHARED_COUNT_START = 'PRODUCT_SHARED_COUNT_START'
export const PRODUCT_SHARED_COUNT_SUCCESS = 'PRODUCT_SHARED_COUNT_SUCCESS'
export const PRODUCT_SHARED_COUNT_FAIL = 'PRODUCT_SHARED_COUNT_FAIL'
export const PRODUCT_SHARED_COUNT_END = 'PRODUCT_SHARED_COUNT_END'
/** 产品详情分享统计 */

/** 保费试算 */
export const PREMIUM_CALC_START = 'PREMIUM_CALC_START'
export const PREMIUM_CALC_SUCCESS = 'PREMIUM_CALC_SUCCESS'
export const PREMIUM_CALC_FAIL = 'PREMIUM_CALC_FAIL'
export const PREMIUM_CALC_END = 'PREMIUM_CALC_END'
/** 保费试算 */

// 保费试算条件
export const PREMIUM_CALC_CONDITION_SET = 'PREMIUM_CALC_CONDITION_SET'
export const PREMIUM_CALC_CONDITION_ADD = 'PREMIUM_CALC_CONDITION_ADD'
export const PREMIUM_CALC_CONDITION_REMOVE = 'PREMIUM_CALC_CONDITION_REMOVE'
export const PREMIUM_CALC_CONDITION_UPDATE = 'PREMIUM_CALC_CONDITION_UPDATE'
export const PREMIUM_CALC_CONDITION_CLEAR = 'PREMIUM_CALC_CONDITION_CLEAR'

export const POLICY_INFO_UPDATE = 'POLICY_INFO_UPDATE'
export const POLICY_HOLDER_UPDATE = 'POLICY_HOLDER_UPDATE'
export const POLICY_INSURANTS_UPDATE = 'POLICY_INSURANTS_UPDATE'
export const POLICY_EXTRAINFO_UPDATE = 'POLICY_EXTRAINFO_UPDATE'
export const POLICY_SINGLE_INSURANT_UPDATE = 'POLICY_SINGLE_INSURANT_UPDATE'
export const POLICY_SINGLE_INSURANT_ADD = 'POLICY_SINGLE_INSURANT_ADD'
export const POLICY_SINGLE_INSURANT_REMOVE = 'POLICY_SINGLE_INSURANT_REMOVE'
export const POLICY_MULTI_INSURANT_SET = 'POLICY_MULTI_INSURANT_SET'
export const POLICY_UPDATE = 'POLICY_UPDATE'
export const POLICY_CLEAR = 'POLICY_CLEAR'
export const POLICY_CLEAREXCEPT_POLICY = 'POLICY_CLEAREXCEPT_POLICY'
export const POLICY_INSURER = 'POLICY_INSURER'
export const POLICY_APPLICANT = 'POLICY_APPLICANT'

/** 获取省市列表 */
export const CITY_LIST_GET_START = 'CITY_LIST_GET_START'
export const CITY_LIST_GET_SUCCESS = 'CITY_LIST_GET_SUCCESS'
export const CITY_LIST_GET_FAIL = 'CITY_LIST_GET_FAIL'
export const CITY_LIST_GET_END = 'CITY_LIST_GET_END'
export const CITY_LIST_POST_SUCCESS = 'CITY_LIST_POST_SUCCESS'
/** 获取省市列表 */

// 获取产品详情
export const PRODUCT_DETAIL_GET_START = 'PRODUCT_DETAIL_GET_START'
export const PRODUCT_DETAIL_GET_SUCCESS = 'PRODUCT_DETAIL_GET_SUCCESS'
export const PRODUCT_DETAIL_GET_FAIL = 'PRODUCT_DETAIL_GET_FAIL'
export const PRODUCT_DETAIL_GET_END = 'PRODUCT_DETAIL_GET_END'

// 更新客户中心信息
export const CUSTOMER_INFO_UPDATE_START = 'CUSTOMER_INFO_UPDATE_START'
export const CUSTOMER_INFO_UPDATE_SUCCESS = 'CUSTOMER_INFO_UPDATE_SUCCESS'
export const CUSTOMER_INFO_UPDATE_FAIL = 'CUSTOMER_INFO_UPDATE_FAIL'
export const CUSTOMER_INFO_UPDATE_END = 'CUSTOMER_INFO_UPDATE_END'

// ProductDetail.js
export const PRODUCT_DETAIL_SET_INFO = 'PRODUCT_DETAIL_SET_INFO'
export const PRODUCT_DETAIL_RESET_INFO = 'PRODUCT_DETAIL_RESET_INFO'
export const PRODUCT_DETAIL_SET_CURRENTCODE = 'PRODUCT_DETAIL_SET_CURRENTCODE'

/** 获取验证码 */
export const SECURITY_CODE_GET_START = 'SECURITY_CODE_GET_START'
export const SECURITY_CODE_GET_SUCCESS = 'SECURITY_CODE_GET_SUCCESS'
export const SECURITY_CODE_GET_FAIL = 'SECURITY_CODE_GET_FAIL'
export const SECURITY_CODE_GET_END = 'SECURITY_CODE_GET_END'
/** 获取验证码 */

/** 获取职业列表 */
export const PROFESSION_LIST_GET_START = 'PROFESSION_LIST_GET_START'
export const PROFESSION_LIST_GET_SUCCESS = 'PROFESSION_LIST_GET_SUCCESS'
export const PROFESSION_LIST_GET_FAIL = 'PROFESSION_LIST_GET_FAIL'
export const PROFESSION_LIST_GET_END = 'PROFESSION_LIST_GET_END'
/** 获取职业列表 */

/** 请求支付信息 */
export const LANCH_OUTORDER_TYPE = 'LANCH_OUTORDER_TYPE'
export const LANCH_PAY_START = 'LANCH_PAY_START'
export const LANCH_PAY_SUCCESS = 'LANCH_PAY_SUCCESS'
export const LANCH_PAY_FAIL = 'LANCH_PAY_FAIL'
export const LANCH_PAY_END = 'LANCH_PAY_END'
export const PAYTYPE_GET_SUCCESS = 'PAYTYPE_GET_SUCCESS'
export const PAYTYPE_GET_FAIL = 'PAYTYPE_GET_FAIL'
/** 请求支付信息 */

export const PRODUCT_DETAIL_LOADER_SUCCESS = 'PRODUCT_DETAIL_LOADER_SUCCESS'

/** 取消/收藏产品 */
// export const STAR_SET_START = 'STAR_SET_START'
// export const STAR_SET_SUCCESS = 'STAR_SET_SUCCESS'
// export const STAR_SET_FAIL = 'STAR_SET_FAIL'
// export const STAR_SET_END = 'STAR_SET_END'
// export const STAR_RESET = 'STAR_RESET'
/** 取消/收藏产品 */

