/** 获取产品列表 */
export const PRODUCT_LIST_CLEAR = 'PRODUCT_LIST_CLEAR'
export const PRODUCT_LIST_GET_START = 'PRODUCT_LIST_GET_START'
export const PRODUCT_LIST_GET_SUCCESS = 'PRODUCT_LIST_GET_SUCCESS'
export const PRODUCT_LIST_GET_FAIL = 'PRODUCT_LIST_GET_FAIL'
export const PRODUCT_LIST_GET_END = 'PRODUCT_LIST_GET_END'
export const PRODUCT_LIST_LOADING_START = 'PRODUCT_LIST_LOADING_START'
export const PRODUCT_LIST_LOADING_SUCCESS = 'PRODUCT_LIST_LOADING_SUCCESS'
export const PRODUCT_LIST_LOADING_FAIL = 'PRODUCT_LIST_LOADING_FAIL'
export const PRODUCT_LIST_LOADING_END = 'PRODUCT_LIST_LOADING_END'



export const PRODUCT_LIST_CURRENT_TAB_SET = 'PRODUCT_LIST_CURRENT_TAB_SET'
